### PR TITLE
Update SuperAPI.lua

### PR DESCRIPTION
**Pull request by ghost**
Fix for spell linking in chat.
Hopefully v1.17.2 fixes the issue but if not then this can help others fix the issue on their end until that time.

### CODE REVIEW

**Comment by balakethelock** [comment]
If you can make it into a setting to disable or enable the feature: Shift click a spell in spellbook to link it to chat

**Comment by ghost** [comment]
My apologies but I don't entirely understand what you'd want me to do?
Which feature is unavailable by commenting out those two lines?
The benefit is expected behavior (being able to shift click spells from spellbook and have them show up properly in chat) while the downside is something that I am still trying to figure out.
I'm uncertain as to which feature is disabled/removed with this change.  Since you are the author maybe poke me here or on Discord with the info?
I'm unsure about the release date of v1.17.2 as things seem to be in flux and an Oct 31st release date may or may not happen.  I'd like this resolved for everyone if at all possible as most players may be unaware of the issue being caused by SuperWoW/SuperAPI.

**Comment by balakethelock** [comment]
This is a vanilla 1.12.1 mod and on 1.12.1 the feature works great to retro-port exactly the robust spell links feature from future expansions, so I don't know what you mean by 1.17.2 release, can you be more specific? 🙂

Sarcasm off, the spell links feature of superwow works fine. The spell link correctly gets sent in chat by Superapi, and it's supposed to be made clickable by Superwow through the SetHyperlink function which is called by ChatFrame_OnHyperlinkShow. The server you're playing on has hooked ChatFrame_OnHyperlinkShow in a custom way and that makes the spell links unclickable.

Not a superapi or superwow problem.

**Comment by ghost** [comment]
I'm sure you could figure a way to detect if the addon is running on Turtle WoW and provide a branching adjustment to disable those two lines to make sure spell linking works as expected.
If this isn't something that can be done, feel free to close the pull request and I'll just point people to my Twow-specific fork until after the next patch when (hopefully) this behavior can be standardized.
I'd prefer not to have a fork for something so simple to modify, but so be it.
I wasn't aware of anyone outside of Turtle WoW using SuperAPI or SuperWoW on other vanilla servers.  If it is being kept compatible with v1.12.1 vanilla servers (rather than just Turtle WoW) then that is understandable.

**Comment by ghost** [comment]
Updated documentation to specify what my fork is for until this issue can be fully resolved server-side.

**Pull request closed without merging**
